framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            amqp_user:
                dsn: '%env(string:MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: '%env(string:MESSENGER_VHOST)%'
                    exhange:
                        name: '%env(string:MESSENGER_EXCHANGE)%'
                        type: direct
                    queues:
                        user_queue:
                            binding_keys: [user_queue]
                    auto_setup: true

        routing:
            # Route your messages to the transports
            'App\Messenger\Message\UserRegisteredMessage': amqp_user
