version: '3.5'

services:
  rabbit:
    container_name: symfony-api-platform-rabbitmq
    build:
      context: ./docker
      args:
        UID: ${HOST_UID}
    volumes:
      - ./docker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672 # puertoLocal:puertoContenedor // puerto de la cola de mensajería
      - 15672:15672 # puertoLocal:puertoContenedor // puerto de la interfaz gráfica
    networks:
      - api-network

networks:
  api-network:
    external: true