framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        failure_transport: failed
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # sync: 'sync://'
            amqp_user:
                dsn: '%env(string:MESSENGER_TRANSPORT_DSN)%'
                serializer: 'Mailer\Serializer\Messenger\EventSerializer'
                #estrategia de reintentos
                retry_strategy:
                    max_retries: 1 #number of tries
                    delay: 1000  #delay between launches (ms)
                    multiplier: 1 #multiplier of delay
                options:
                    vhost: '%env(string:MESSENGER_VHOST)%'
                    exhange:
                        name: '%env(string:MESSENGER_EXCHANGE)%'
                        type: direct
                    queues:
                        user_queue:
                            binding_keys: [user_queue]
                    auto_setup: true
            failed:
                dsn: 'doctrine://default?queue_name=failed' #almacenamos en una trabla los mensajes de envío fallido y esa cola es "failed"

        routing:
            # Route your messages to the transports
            'Mailer\Messenger\Message\UserRegisteredMessage': amqp_user
